version: '3'

services:
  app:
    container_name: back-php
    image: bloondedocker/php8.1
  #  environment:
 #     - APACHE_RUN_USER=#${UID}
  #    - APACHE_RUN_GROUP=#${UID}
    working_dir: /var/www/html
    volumes:
      - ./docker-laravel/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./:/var/www/html/
    ports:
      - 5000:80
      - 5173:5173
    networks:
      - servidor-web
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file: ./.env
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - 6000:3306
    networks:
      - servidor-web
    restart: always

networks:
  servidor-web:
volumes:
  dbdata:
